# -*- mode: ruby -*-
# vi: set f=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "chad-thompson/ubuntu-trusty64-gui"
    config.vm.synced_folder "shared", "/tmp/shared"

    config.vm.provider :virtualbox do |vbox|
        vbox.gui = true
        vbox.cpus = 2
    end

    config.vm.define "master" do |master|
        master.vm.hostname = "enterprisemaster.qac.local"
        master.vm.network :public_network, ip: "192.168.1.42"
        master.vm.provision :shell, path: "bootstrap_master.sh"

        master.vm.provider :virtualbox do |vbox|
            vbox.name = "Enterprise_Master"
			vbox.memory = 4320
        end
    end

    config.vm.define "agent" do |agent|
        agent.vm.hostname = "enterpriseagent1.qac.local"
        agent.vm.network :public_network, ip: "192.168.1.43"
        #agent.vm.provision :shell, path: "bootstrap_agent.sh"

        agent.vm.provider :virtualbox do |vbox|
            vbox.name = "Enterprise_Agent"
			vbox.memory = 2048
        end
    end
	
end