# -*- mode: ruby -*-
# vi: set f=ruby :

Vagrant.configure(2) do |config|

	config.vm.box = "chad-thompson/ubuntu-trusty64-gui"
	
	config.vm.hostname = "agent2.qac.local"
	config.vm.network :public_network, ip: "192.168.1.27"
	
	config.vm.provision :shell, path: "bootstrap_agent2.sh"

	config.vm.synced_folder "shared", "/tmp/shared"
	
	config.vm.provider :virtualbox do |vbox|
		vbox.gui = true
		vbox.memory = 4096
		vbox.cpus = 2
		vbox.name = "Vagrant Up Agent 2"
	end
	
end